### PR TITLE
Fix typo and add Device, AppData, Log, FileStream to API2

### PR DESCRIPTION
**Pull request by mooner1022**
Fixed typo where `activityBackPressed` is written as `activityBackProssed`

### CODE REVIEW

**Comment by mooner1022** [comment]
Requested by `VioletXF`, added Device, AppData, Log, FileStream to API2

**Comment by franknoh** [comment]
내일 확인후 merge 하겠습니다

**Comment by franknoh** [comment]
full.html, sidebar 수정후 merge하겠습니다.

**Comment by franknoh** [comment]
@nolbo 확인좀

**Pull request merged**
